const userActions = {
    FETCH_USER_START: 'FETCH_USER_START',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    FETCH_TOTAL_PAGE_COUNT_START: 'FETCH_TOTAL_PAGE_COUNT_START',
    FETCH_TOTAL_PAGE_COUNT_SUCCESS: 'FETCH_TOTAL_PAGE_COUNT_SUCCESS',
    FETCH_TOTAL_PAGE_COUNT_FAILURE: 'FETCH_TOTAL_PAGE_COUNT_FAILURE',
    FETCH_MORE_USERS_START: 'FETCH_MORE_USERS_START',
    FETCH_MORE_USERS_SUCCESS: 'FETCH_MORE_USERS_SUCCESS',
    FETCH_MORE_USERS_FAILURE: 'FETCH_MORE_USERS_FAILURE',
    INCREASE_PAGE_COUNT: 'INCREASE_PAGE_COUNT',
    ALL_USERS_FETCHED: 'ALL_USERS_FETCHED'
}

export default userActions